[build]
  command = "NODE_ENV=production gatsby build"
  publish = "public/"

[template]
  incoming-hooks = ["Ghost"]

[[redirects]]
  from = "*"
  to = "https://blog.ghimiresamip.com.np/blogs"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"