[build]
  command = "NODE_ENV=production gatsby build"
  publish = "public/"

[template]
  incoming-hooks = ["Ghost"]

[[redirects]]
from = "https://blog.ghimiresamip.com.np/blogs/"
to= "https://blog.ghimiresamip.com.np/"
status = 301
force = false