[build]
  command = "NODE_ENV=production gatsby build"
  publish = "public/"

[template]
  incoming-hooks = ["Ghost"]

[[redirects]]
from = "https://blog.ghimiresamip.com.np/"
to = "https://blog.ghimiresamip.com.np/blogs/"
status = 200
force = false