[build]
  command = "NODE_ENV=production gatsby build"
  publish = "public/"

[template]
  incoming-hooks = ["Ghost"]

## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/*"
  to = "https://ghimiresamip.com.np"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"